### ISSUE TITLE
Build fails: Connection refused

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-dns#1]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
  - ansible_version=">=2.2,<2.3"
  - ansible_version=">=2.3,<2.4"
  - ansible_version=">=2.4,<2.5"
```

##### CONFIGURATION
Nothing worth mentioning.

##### OS / ENVIRONMENT
Any OS

##### SUMMARY
This role fails to download from an external source:
```
- name: get most recent version of the hints/root file
  get_url:
    url: ftp://ftp.internic.net/domain/named.root
    dest: "{{ dns_zonesdir[ansible_distribution] | default(dns_zonesdir['default'] ) }}/named.root"
  when:
    - dns_caching_dns == true
  notify:
    reload zones
```

##### STEPS TO REPRODUCE
Run the role or look at https://travis-ci.org/robertdebock/ansible-role-dns/jobs/350698677

##### EXPECTED RESULTS
Working code.

##### ACTUAL RESULTS
```
    fatal: [dns-alpine-3.6]: FAILED! => {"changed": false, "dest": "/var/named/named.root", "failed": true, "msg": "Request failed: <urlopen error ftp error: [Errno 111] Connection refused>", "state": "absent", "url": "ftp://ftp.internic.net/domain/named.root"}
```
