### ISSUE TITLE
[DOC] Provide more guidance on zone files

### ISSUE THREAD

**Issue by blaisep** [robertdebock/ansible-role-dns#10]
**Is your feature request related to a problem? Please describe.**

I'm not familiar with the structure of the YAML zone file and I have trouble following the example. I wonder if we could include sample zone files for different scenarios.

**Describe the solution you'd like**

I would like to find a zone file similar to my use case(s) and know which items to modify to my specifics. For example, today I'm creating a home lab in a subdomain of my personal `controlplane.info` domain

Or...  
a link to a resource that can consume/create zone files in various formats (similar to https://github.com/barnybug/cli53 )

Or...
A filter that can read BIND txt (pandoc ?)

Or...
a link to a tutorial with a description of the structure of the file and which parts to change.
(like https://www.digitalocean.com/community/tutorials/how-to-deploy-and-manage-your-dns-using-octodns-on-ubuntu-18-04)

I don't want to create extra work, and I think this is probably only an issue for N00B users of the role.

**Describe alternatives you've considered**
I have tried other Ansible roles, but no one seems to have the consistency and rigor that @robertdebock provides, so I end up with a mess on my hands.

**Additional context**

If you tell me the kind of approach you would like to take and I find something that aligns with that, I'm happy to submit a PR.

This is the part of the of the `defaults/main.yml` that I changed:

```
  - name: lab.controlplane.info.
    ttl: 600
    ns:
      - name: ns.lab.controlplane.info
    mx:
      - name: mail1.lab.controlplane.info.
        priority: 10
      - name: mail2.lab.controlplane.info.
        priority: 20
    records:
      - name: ns
        value: 192.168.254.27
      - name: git
        value: 192.168.254.19
      - name: dl380
        value: 192.168.254.27
  - name: forwarded.lab.controlplane.info.
    ns:
      - name: forwarded.lab.controlplane.info.
    records:
      - name: ns
        value: 192.168.254.27
    dns_zone_forwarders:
      - 9.9.9.9
      - 8.8.8.8
# An optional list of acls to allow recursion. ("any" and "none" are always available.)
dns_allow_recursion:
  - none
# An optional setting to forward traffic to other DNS servers.
dns_options_forwarders:
#   - 1.1.1.1
  - 8.8.8.8
```

And I got this error:

```
fatal: [ns]: FAILED! => {"changed": false, "checksum": "74c5e515d1ff9789e7cfa5d2528c364c5c9fdc4c", "exit_status": 1, "msg": "failed to validate", "stderr": "_default/lab.controlplane.info./IN: empty label\n_default/forwarded.lab.controlplane.info./IN: empty label\n", "stderr_lines": ["_default/lab.controlplane.info./IN: empty label", "_default/forwarded.lab.controlplane.info./IN: empty label"], "stdout": "zone localhost/IN: loaded serial 1\nzone 127.in-addr.arpa/IN: loaded serial 1\nzone 0.in-addr.arpa/IN: loaded serial 1\nzone 255.in-addr.arpa/IN: loaded serial 1\ndns_master_load: /var/named/lab.controlplane.info..conf:2: empty label\ndns_master_load: /var/named/lab.controlplane.info..conf:4: extra input text\n/var/named/lab.controlplane.info..conf:11: no current owner name\n/var/named/lab.controlplane.info..conf:13: no current owner name\n/var/named/lab.controlplane.info..conf:14: no current owner name\nzone lab.controlplane.info/IN: loading from master file /var/named/lab.controlplane.info..conf failed: empty label\nzone lab.controlplane.info/IN: not loaded due to errors.\ndns_master_load: /var/named/forwarded.lab.controlplane.info..conf:2: empty label\ndns_master_load: /var/named/forwarded.lab.controlplane.info..conf:4: extra input text\n/var/named/forwarded.lab.controlplane.info..conf:11: no current owner name\nzone forwarded.lab.controlplane.info/IN: loading from master file /var/named/forwarded.lab.controlplane.info..conf failed: empty label\nzone forwarded.lab.controlplane.info/IN: not loaded due to errors.\n", "stdout_lines": ["zone localhost/IN: loaded serial 1", "zone 127.in-addr.arpa/IN: loaded serial 1", "zone 0.in-addr.arpa/IN: loaded serial 1", "zone 255.in-addr.arpa/IN: loaded serial 1", "dns_master_load: /var/named/lab.controlplane.info..conf:2: empty label", "dns_master_load: /var/named/lab.controlplane.info..conf:4: extra input text", "/var/named/lab.controlplane.info..conf:11: no current owner name", "/var/named/lab.controlplane.info..conf:13: no current owner name", "/var/named/lab.controlplane.info..conf:14: no current owner name", "zone lab.controlplane.info/IN: loading from master file /var/named/lab.controlplane.info..conf failed: empty label", "zone lab.controlplane.info/IN: not loaded due to errors.", "dns_master_load: /var/named/forwarded.lab.controlplane.info..conf:2: empty label", "dns_master_load: /var/named/forwarded.lab.controlplane.info..conf:4: extra input text", "/var/named/forwarded.lab.controlplane.info..conf:11: no current owner name", "zone forwarded.lab.controlplane.info/IN: loading from master file /var/named/forwarded.lab.controlplane.info..conf failed: empty label", "zone forwarded.lab.controlplane.info/IN: not loaded due to errors."]}
```

**Comment by robertdebock** [comment]
Clear and improving documentation is a great plan. I'll debug your posted example, fix and include it in testing and documentation.

**Comment by robertdebock** [comment]
I've changed your dns configuration a bit into this working version:

```
      # Added `dns_zones`.
      dns_zones:
        # Remove the trailing period (.).
        - name: lab.controlplane.info
          ttl: 600
          ns:
            # Added a trailing period (.).
            - name: ns.lab.controlplane.info.
          mx:
            - name: mail1.lab.controlplane.info.
              priority: 10
            - name: mail2.lab.controlplane.info.
              priority: 20
          records:
            - name: ns
              value: 192.168.254.27
            - name: git
              value: 192.168.254.19
            - name: dl380
              value: 192.168.254.27
            # Added mail1 because is't mentioned in the mx records
            - name: mail1
              value: 192.168.123.123
            # Added mail2 because is't mentioned in the mx records
            - name: mail2
              value: 192.168.123.123
        # Remove the trailing period (.).
        - name: forwarded.lab.controlplane.info
          ns:
            - name: forwarded.lab.controlplane.info.
          records:
            - name: ns
              value: 192.168.254.27
            # Added ns because it's mentioned in the ns records
            - name: "@"
              value: 192.168.123.123
          dns_zone_forwarders:
            - 9.9.9.9
            - 8.8.8.8
      # An optional list of acls to allow recursion. ("any" and "none" are always available.)
      dns_allow_recursion:
        - none
      # An optional setting to forward traffic to other DNS servers.
      dns_options_forwarders:
      #   - 1.1.1.1
        - 8.8.8.8
```

Is it okay if I include this example in the documentation?
