### ISSUE TITLE
Add ability to set zone type

### ISSUE THREAD

**Issue by BenWaller** [robertdebock/ansible-role-dns#9]
I would like to be able to set up different types of zones like forward type zones. The zone type is hard coded in the template here https://github.com/robertdebock/ansible-role-dns/blob/master/templates/named.conf.j2#L60 You would also need conditionally remove the file entry since you don't need one for a forward zone

There are several more possible zone types allowed by bind. https://www.zytrax.com/books/dns/ch7/zone.html

A config like this would result in a forward only zone 
```
  - name: forwarded.example.com
    type: forward
    dns_zone_forwarders:
      - 1.1.1.1
      - 8.8.8.8
```

Output in named.conf 
```
zone "forwarded.example.com" {
  type forward;
  forwarders {
    1.1.1.1;
    8.8.8.8;
  };
};
```
